export const TeamListFull = [
  {
    id: 'hawks',
    teamName: 'Atlanta Hawks',
    nickname: 'Hawks',
    conference: 'East',
  },
  {
    id: 'celtics',
    teamName: 'Boston Celtics',
    nickname: 'Celtics',
    conference: 'East',
  },
  {
    id: 'nets',
    teamName: 'Brooklyn Nets',
    nickname: 'Nets',
    conference: 'East',
  },
  {
    id: 'hornets',
    teamName: 'Charlotte Hornets',
    nickname: 'Hornets',
    conference: 'East',
  },
  {
    id: 'bulls',
    teamName: 'Chicago Bulls',
    nickname: 'Bulls',
    conference: 'East',
  },
  {
    id: 'cavaliers',
    teamName: 'Cleveland Cavaliers',
    nickname: 'Cavaliers',
    conference: 'East',
  },
  {
    id: 'mavericks',
    teamName: 'Dallas Mavericks',
    nickname: 'Mavericks',
    conference: 'West',
  },
  {
    id: 'nuggets',
    teamName: 'Denver Nuggets',
    nickname: 'Nuggets',
    conference: 'West',
  },
  {
    id: 'pistons',
    teamName: 'Detroit Pistons',
    nickname: 'Pistons',
    conference: 'East',
  },
  {
    id: 'warriors',
    teamName: 'Golden State Warriors',
    nickname: 'Warriors',
    conference: 'West',
  },
  {
    id: 'rockets',
    teamName: 'Houston Rockets',
    nickname: 'Rockets',
    conference: 'West',
  },
  {
    id: 'pacers',
    teamName: 'Indiana Pacers',
    nickname: 'Pacers',
    conference: 'East',
  },
  {
    id: 'clippers',
    teamName: 'Los Angeles Clippers',
    nickname: 'Clippers',
    conference: 'West',
  },
  {
    id: 'lakers',
    teamName: 'Los Angeles Lakers',
    nickname: 'Lakers',
    conference: 'West',
  },
  {
    id: 'grizzlies',
    teamName: 'Memphis Grizzlies',
    nickname: 'Grizzlies',
    conference: 'West',
  },
  { id: 'heat', teamName: 'Miami Heat', nickname: 'Heat', conference: 'East' },
  {
    id: 'bucks',
    teamName: 'Milwaukee Bucks',
    nickname: 'Bucks',
    conference: 'East',
  },
  {
    id: 'timberwolves',
    teamName: 'Minnesota Timberwolves',
    nickname: 'Timberwolves',
    conference: 'West',
  },
  {
    id: 'pelicans',
    teamName: 'New Orleans Pelicans',
    nickname: 'Pelicans',
    conference: 'West',
  },
  {
    id: 'knicks',
    teamName: 'New York Knicks',
    nickname: 'Knicks',
    conference: 'East',
  },
  {
    id: 'thunder',
    teamName: 'Oklahoma City Thunder',
    nickname: 'Thunder',
    conference: 'West',
  },
  {
    id: 'magic',
    teamName: 'Orlando Magic',
    nickname: 'Magic',
    conference: 'East',
  },
  {
    id: '76ers',
    teamName: 'Philadelphia 76ers',
    nickname: 'Sixers',
    conference: 'East',
  },
  {
    id: 'suns',
    teamName: 'Phoenix Suns',
    nickname: 'Suns',
    conference: 'West',
  },
  {
    id: 'trail blazers',
    teamName: 'Portland Trail Blazers',
    nickname: 'Blazers',
    conference: 'West',
  },
  {
    id: 'kings',
    teamName: 'Sacramento Kings',
    nickname: 'Kings',
    conference: 'West',
  },
  {
    id: 'spurs',
    teamName: 'San Antonio Spurs',
    nickname: 'Spurs',
    conference: 'West',
  },
  {
    id: 'raptors',
    teamName: 'Toronto Raptors',
    nickname: 'Raptors',
    conference: 'East',
  },
  { id: 'jazz', teamName: 'Utah Jazz', nickname: 'Jazz', conference: 'West' },
  {
    id: 'wizards',
    teamName: 'Washington Wizards',
    nickname: 'Wizards',
    conference: 'East',
  },
];

export const TeamMap = Object.fromEntries(TeamListFull.map((t) => [t.id, t]));
