export const TeamListFull = [
  { id: 'hawks', teamName: 'Atlanta Hawks', nickname: 'Hawks' },
  { id: 'celtics', teamName: 'Boston Celtics', nickname: 'Celtics' },
  { id: 'nets', teamName: 'Brooklyn Nets', nickname: 'Nets' },
  { id: 'hornets', teamName: 'Charlotte Hornets', nickname: 'Hornets' },
  { id: 'bulls', teamName: 'Chicago Bulls', nickname: 'Bulls' },
  { id: 'cavaliers', teamName: 'Cleveland Cavaliers', nickname: 'Cavaliers' },
  { id: 'mavericks', teamName: 'Dallas Mavericks', nickname: 'Mavericks' },
  { id: 'nuggets', teamName: 'Denver Nuggets', nickname: 'Nuggets' },
  { id: 'pistons', teamName: 'Detroit Pistons', nickname: 'Pistons' },
  { id: 'warriors', teamName: 'Golden State Warriors', nickname: 'Warriors' },
  { id: 'rockets', teamName: 'Houston Rockets', nickname: 'Rockets' },
  { id: 'pacers', teamName: 'Indiana Pacers', nickname: 'Pacers' },
  { id: 'clippers', teamName: 'Los Angeles Clippers', nickname: 'Clippers' },
  { id: 'lakers', teamName: 'Los Angeles Lakers', nickname: 'Lakers' },
  { id: 'grizzlies', teamName: 'Memphis Grizzlies', nickname: 'Grizzlies' },
  { id: 'heat', teamName: 'Miami Heat', nickname: 'Heat' },
  { id: 'bucks', teamName: 'Milwaukee Bucks', nickname: 'Bucks' },
  {
    id: 'timberwolves',
    teamName: 'Minnesota Timberwolves',
    nickname: 'Timberwolves',
  },
  { id: 'pelicans', teamName: 'New Orleans Pelicans', nickname: 'Pelicans' },
  { id: 'knicks', teamName: 'New York Knicks', nickname: 'Knicks' },
  { id: 'thunder', teamName: 'Oklahoma City Thunder', nickname: 'Thunder' },
  { id: 'magic', teamName: 'Orlando Magic', nickname: 'Magic' },
  { id: 'sixers', teamName: 'Philadelphia 76ers', nickname: 'Sixers' },
  { id: 'suns', teamName: 'Phoenix Suns', nickname: 'Suns' },
  { id: 'blazers', teamName: 'Portland Trail Blazers', nickname: 'Blazers' },
  { id: 'kings', teamName: 'Sacramento Kings', nickname: 'Kings' },
  { id: 'spurs', teamName: 'San Antonio Spurs', nickname: 'Spurs' },
  { id: 'raptors', teamName: 'Toronto Raptors', nickname: 'Raptors' },
  { id: 'jazz', teamName: 'Utah Jazz', nickname: 'Jazz' },
  { id: 'wizards', teamName: 'Washington Wizards', nickname: 'Wizards' },
];

export const TeamMap = Object.fromEntries(TeamListFull.map((t) => [t.id, t]));
