export const TEAM_LOGO_MAP = {
  Hawks: 'hawks',
  Celtics: 'celtics',
  Nets: 'nets',
  Hornets: 'hornets',
  Bulls: 'bulls',
  Cavaliers: 'cavaliers',
  Mavericks: 'mavericks',
  Nuggets: 'nuggets',
  Pistons: 'pistons',
  Warriors: 'warriors',
  Rockets: 'rockets',
  Pacers: 'pacers',
  Clippers: 'clippers',
  Lakers: 'lakers',
  Grizzlies: 'grizzlies',
  Heat: 'heat',
  Bucks: 'bucks',
  Timberwolves: 'timberwolves',
  Pelicans: 'pelicans',
  Knicks: 'knicks',
  Thunder: 'thunder',
  Magic: 'magic',
  Sixers: 'sixers',
  '76ers': 'sixers',
  Suns: 'suns',
  BTrailBlazers: 'blazers',
  'Trail Blazers': 'blazers',
  trailblazers: 'blazers',
  Blazers: 'blazers',
  Kings: 'kings',
  Spurs: 'spurs',
  Raptors: 'raptors',
  Jazz: 'jazz',
  Wizards: 'wizards',
  // Full team names
  'Atlanta Hawks': 'hawks',
  'Boston Celtics': 'celtics',
  'Brooklyn Nets': 'nets',
  'Charlotte Hornets': 'hornets',
  'Chicago Bulls': 'bulls',
  'Cleveland Cavaliers': 'cavaliers',
  'Dallas Mavericks': 'mavericks',
  'Denver Nuggets': 'nuggets',
  'Detroit Pistons': 'pistons',
  'Golden State Warriors': 'warriors',
  'Houston Rockets': 'rockets',
  'Indiana Pacers': 'pacers',
  'Los Angeles Clippers': 'clippers',
  'LA Clippers': 'clippers',
  'Los Angeles Lakers': 'lakers',
  'Memphis Grizzlies': 'grizzlies',
  'Miami Heat': 'heat',
  'Milwaukee Bucks': 'bucks',
  'Minnesota Timberwolves': 'timberwolves',
  'New Orleans Pelicans': 'pelicans',
  'New York Knicks': 'knicks',
  'Oklahoma City Thunder': 'thunder',
  'Orlando Magic': 'magic',
  'Philadelphia 76ers': 'sixers',
  'Phoenix Suns': 'suns',
  'Portland Trail Blazers': 'blazers',
  'Sacramento Kings': 'kings',
  'San Antonio Spurs': 'spurs',
  'Toronto Raptors': 'raptors',
  'Utah Jazz': 'jazz',
  'Washington Wizards': 'wizards',
  // Abbreviations
  ATL: 'hawks',
  BOS: 'celtics',
  BKN: 'nets',
  CHA: 'hornets',
  CHI: 'bulls',
  CLE: 'cavaliers',
  DAL: 'mavericks',
  DEN: 'nuggets',
  DET: 'pistons',
  GSW: 'warriors',
  HOU: 'rockets',
  IND: 'pacers',
  LAC: 'clippers',
  LAL: 'lakers',
  MEM: 'grizzlies',
  MIA: 'heat',
  MIL: 'bucks',
  MIN: 'timberwolves',
  NOP: 'pelicans',
  NYK: 'knicks',
  OKC: 'thunder',
  ORL: 'magic',
  PHI: 'sixers',
  PHX: 'suns',
  POR: 'blazers',
  SAC: 'kings',
  SAS: 'spurs',
  TOR: 'raptors',
  UTA: 'jazz',
  WAS: 'wizards',
};

export function getTeamLogoFilename(teamName) {
  if (!teamName) return 'default';
  return TEAM_LOGO_MAP[teamName] || teamName.toLowerCase().replace(/\s+/g, '');
}
